import { StyleSheet } from "react-native";

import { fontFamily } from "@/theme/fonts";
import { borderRadius, colors, spacing } from "@/theme/tokens";

export function createDetailsLineStyle(
  pickupDotY: number,
  destinationDotY: number,
) {
  return StyleSheet.create({
    detailsLine: {
      height: Math.max(0, destinationDotY - pickupDotY - 12),
      top: pickupDotY + 12,
    },
  }).detailsLine;
}

export const styles = StyleSheet.create({
  arrival: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    lineHeight: 24,
  },
  arrivalLongDuration: {
    marginTop: spacing[1],
  },
  backButton: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: borderRadius.large,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  controlRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    left: spacing[5],
    position: "absolute",
    right: spacing[5],
    top: spacing[5],
  },
  content: { flex: 1 },
  detailsCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.large,
    marginTop: spacing[5],
    padding: spacing[4],
  },
  emptyStepsText: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing[3],
  },
  detailsLine: {
    backgroundColor: colors.border,
    left: 27,
    position: "absolute",
    width: 2,
  },
  destinationDot: {
    backgroundColor: colors.text,
    borderRadius: 2,
    height: 12,
    marginRight: spacing[3],
    width: 12,
  },
  footer: {
    backgroundColor: colors.background,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    padding: spacing[5],
  },
  footerButton: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: borderRadius.large,
    flexDirection: "row",
    gap: spacing[3],
    height: 72,
    justifyContent: "center",
  },
  footerButtonPressed: { opacity: 0.85 },
  map: { flex: 1 },
  mapArea: { flex: 1 },
  mapFallback: {
    alignItems: "center",
    backgroundColor: colors.surface,
    flex: 1,
    justifyContent: "center",
    padding: spacing[6],
  },
  mapFallbackText: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  mapPin: {
    alignItems: "center",
    backgroundColor: colors.text,
    borderColor: colors.background,
    borderRadius: 22,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  mapTruck: {
    alignItems: "center",
    backgroundColor: colors.accent,
    borderColor: colors.background,
    borderRadius: 22,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  modeButton: {
    alignItems: "center",
    borderColor: colors.border,
    borderRadius: borderRadius.large,
    borderWidth: 1,
    flex: 1,
    height: 43,
    justifyContent: "center",
  },
  modeButtonActive: {
    backgroundColor: "#FFF2ED",
    borderColor: colors.accent,
  },
  modeLabel: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 16,
    lineHeight: 24,
  },
  modeLabelActive: { color: colors.accent },
  modes: {
    flexDirection: "row",
    gap: spacing[2],
    marginTop: spacing[5],
  },
  pickupDot: {
    backgroundColor: colors.accent,
    borderRadius: 6,
    height: 12,
    marginRight: spacing[3],
    width: 12,
  },
  routeCard: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    bottom: 0,
    height: "58%",
    position: "absolute",
    width: "100%",
  },
  routeCardContent: {
    paddingBottom: spacing[5],
    paddingHorizontal: spacing[5],
    paddingTop: spacing[3],
  },
  routeHandle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 2,
    height: 4,
    width: 48,
  },
  routeMeta: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing[4],
  },
  routeMetaLongDuration: {
    alignItems: "flex-start",
    flexDirection: "column",
  },
  routeName: {
    color: colors.textPlaceholder,
    fontFamily: fontFamily.bold,
    fontSize: 15,
    lineHeight: 22,
  },
  routeTime: {
    color: colors.text,
    fontFamily: fontFamily.extraBold,
    fontSize: 34,
    lineHeight: 48,
  },
  routeTimeLongDuration: {
    fontSize: 38,
    lineHeight: 44,
  },
  row: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 42,
  },
  rowText: {
    color: colors.text,
    flex: 1,
    fontFamily: fontFamily.bold,
    fontSize: 16,
    lineHeight: 23,
  },
  routeSummary: { paddingBottom: spacing[5] },
  screen: { backgroundColor: colors.surface, flex: 1 },
  step: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 70,
  },
  stepContent: {
    flex: 1,
  },
  stepIcon: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 22,
    height: 44,
    justifyContent: "center",
    marginRight: spacing[3],
    width: 44,
  },
  stepSubtitle: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 2,
  },
  stepTitle: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 17,
    lineHeight: 24,
  },
  trafficAlert: {
    alignItems: "center",
    backgroundColor: colors.text,
    borderRadius: borderRadius.large,
    bottom: 242,
    flexDirection: "row",
    gap: spacing[2],
    left: spacing[5],
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    position: "absolute",
  },
  trafficText: {
    color: colors.background,
    fontFamily: fontFamily.bold,
    fontSize: 15,
    lineHeight: 22,
  },
  turnByTurnLabel: {
    color: colors.textPlaceholder,
    fontFamily: fontFamily.bold,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing[5],
  },
});
