export const nunitoSansFonts = {
  'NunitoSans-ExtraLight': require('@/assets/fonts/NunitoSans-ExtraLight.ttf'),
  'NunitoSans-Light': require('@/assets/fonts/NunitoSans-Light.ttf'),
  'NunitoSans-Regular': require('@/assets/fonts/NunitoSans-Regular.ttf'),
  'NunitoSans-Medium': require('@/assets/fonts/NunitoSans-Medium.ttf'),
  'NunitoSans-SemiBold': require('@/assets/fonts/NunitoSans-SemiBold.ttf'),
  'NunitoSans-Bold': require('@/assets/fonts/NunitoSans-Bold.ttf'),
  'NunitoSans-ExtraBold': require('@/assets/fonts/NunitoSans-ExtraBold.ttf'),
  'NunitoSans-Black': require('@/assets/fonts/NunitoSans-Black.ttf'),
  'NunitoSans-ExtraBlack': require('@/assets/fonts/NunitoSansExtraBlack-Regular.ttf'),
  'NunitoSans-Italic': require('@/assets/fonts/NunitoSans-Italic.ttf'),
  'NunitoSans-ExtraLightItalic': require('@/assets/fonts/NunitoSans-ExtraLightItalic.ttf'),
  'NunitoSans-LightItalic': require('@/assets/fonts/NunitoSans-LightItalic.ttf'),
  'NunitoSans-MediumItalic': require('@/assets/fonts/NunitoSans-MediumItalic.ttf'),
  'NunitoSans-SemiBoldItalic': require('@/assets/fonts/NunitoSans-SemiBoldItalic.ttf'),
  'NunitoSans-BoldItalic': require('@/assets/fonts/NunitoSans-BoldItalic.ttf'),
  'NunitoSans-ExtraBoldItalic': require('@/assets/fonts/NunitoSans-ExtraBoldItalic.ttf'),
  'NunitoSans-BlackItalic': require('@/assets/fonts/NunitoSans-BlackItalic.ttf'),
  'NunitoSans-ExtraBlackItalic': require('@/assets/fonts/NunitoSansExtraBlack-Italic.ttf'),
} as const;

export const fontFamily = {
  extraLight: 'NunitoSans-ExtraLight',
  light: 'NunitoSans-Light',
  regular: 'NunitoSans-Regular',
  medium: 'NunitoSans-Medium',
  semiBold: 'NunitoSans-SemiBold',
  bold: 'NunitoSans-Bold',
  extraBold: 'NunitoSans-ExtraBold',
  black: 'NunitoSans-Black',
  extraBlack: 'NunitoSans-ExtraBlack',
  italic: 'NunitoSans-Italic',
  extraLightItalic: 'NunitoSans-ExtraLightItalic',
  lightItalic: 'NunitoSans-LightItalic',
  mediumItalic: 'NunitoSans-MediumItalic',
  semiBoldItalic: 'NunitoSans-SemiBoldItalic',
  boldItalic: 'NunitoSans-BoldItalic',
  extraBoldItalic: 'NunitoSans-ExtraBoldItalic',
  blackItalic: 'NunitoSans-BlackItalic',
  extraBlackItalic: 'NunitoSans-ExtraBlackItalic',
} as const;
